### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by pcs333** [rfsbraz/deleterr#106]
Hi
First time user here, hope someone can help. I have been scratching my head with this error. It works fine if I just run it with sonarr. As soon as I enable radarr in the config I get this error. Thanks 

2024-05-08 16:39:30 - INFO :: media_cleaner.py :: deleterr : Processing library 'Films'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/app/deleterr.py", line 111, in <module>
    main()
  File "/app/app/deleterr.py", line 107, in main
    Deleterr(config)
  File "/app/app/deleterr.py", line 32, in __init__
    self.process_radarr()
  File "/app/app/deleterr.py", line 42, in process_radarr
    saved_space += self.media_cleaner.process_library_movies(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/media_cleaner.py", line 212, in process_library_movies
    movie_activity = self.get_movie_activity(library, movies_library)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/media_cleaner.py", line 58, in get_movie_activity
    return self.tautulli.get_activity(library, movies_library.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 48, in get_activity
    key = self._determine_key(raw_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 98, in _determine_key
    if raw_data[0].get("grandparent_rating_key", "")
       ~~~~~~~~^^^
IndexError: list index out of range

**Comment by rfsbraz** [comment]
This is fixed! Check either `latest` or `0.0.17`.

Thanks for you report!
