### ISSUE TITLE
Getting Resource not Found when trying to delete a show

### ISSUE THREAD

**Issue by lakshyaGoel** [rfsbraz/deleterr#127]
I am using the latest release, and when running with the dry-run as `false`, I get this error. What could be causing this? 

The path for the show is `/mnt/media/TV/Fleabag (2016)`. Could the `(2016)` in the path be causing the erro? If yes, how could it find the details about the show, like the number of episodes and size on the disk? 

```
2024-08-27 21:37:36 - INFO :: deleterr.py :: deleterr : Running version rfsbraz/deleterr:0.0.19
2024-08-27 21:37:36 - INFO :: deleterr.py :: deleterr : Log level set to DEBUG
2024-08-27 21:37:36 - DEBUG :: config.py :: deleterr : Loading configuration from /config/settings.yaml
2024-08-27 21:37:36 - INFO :: deleterr.py :: deleterr : Processing sonarr instance: 'Sonarr'
2024-08-27 21:37:36 - INFO :: media_cleaner.py :: deleterr : Instance has 21 items to process of type 'standard'
2024-08-27 21:37:36 - INFO :: media_cleaner.py :: deleterr : Processing library 'TV Shows'
2024-08-27 21:37:36 - INFO :: media_cleaner.py :: deleterr : Got 0 trakt items to exclude
2024-08-27 21:37:36 - INFO :: media_cleaner.py :: deleterr : Got 16 items in plex library
2024-08-27 21:37:36 - DEBUG :: tautulli.py :: deleterr : Fetching last activity since 2024-05-29 21:37:36.830915
2024-08-27 21:37:36 - DEBUG :: tautulli.py :: deleterr : Fetched 16 items
2024-08-27 21:37:37 - DEBUG :: tautulli.py :: deleterr : [1/2] Processed items
2024-08-27 21:37:37 - DEBUG :: tautulli.py :: deleterr : [2/2] Processed items
2024-08-27 21:37:37 - INFO :: media_cleaner.py :: deleterr : Got 2 items in tautulli activity
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Sorting media by release_year asc
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : The Office (US) has excluded title The Office (US), skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Modern Family watched 5 days ago, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Community has excluded title Community, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Parks and Recreation has excluded title Parks and Recreation, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Brooklyn Nine-Nine (2013) not found in Plex, but has no episodes, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Last Week Tonight with John Oliver watched 7 days ago, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Outlander (2014) not found in Plex, but has no episodes, skipping
2024-08-27 21:37:37 - DEBUG :: media_cleaner.py :: deleterr : Superstore has excluded title Superstore, skipping
2024-08-27 21:37:37 - INFO :: media_cleaner.py :: deleterr : [0/10] Deleting show 'Fleabag' from sonarr instance  'TV Shows' (18.00 GB - 12 episodes)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/app/deleterr.py", line 111, in <module>
    main()
  File "/app/app/deleterr.py", line 107, in main
    Deleterr(config)
  File "/app/app/deleterr.py", line 31, in __init__
    self.process_sonarr()
  File "/app/app/deleterr.py", line 59, in process_sonarr
    saved_space += self.media_cleaner.process_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/media_cleaner.py", line 93, in process_library
    return self.process_shows(
           ^^^^^^^^^^^^^^^^^^^
  File "/app/app/media_cleaner.py", line 124, in process_shows
    saved_space += self.process_show(
                   ^^^^^^^^^^^^^^^^^^
  File "/app/app/media_cleaner.py", line 151, in process_show
    self.delete_show_if_allowed(
  File "/app/app/media_cleaner.py", line 201, in delete_show_if_allowed
    self.delete_series(sonarr_instance, sonarr_show)
  File "/app/app/media_cleaner.py", line 299, in delete_series
    sonarr.upd_episode_monitor([episode["id"] for episode in episodes], False)
  File "/usr/local/lib/python3.12/site-packages/pyarr/sonarr.py", line 168, in upd_episode_monitor
    return self._put(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyarr/request_handler.py", line 160, in _put
    response = _process_response(res)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyarr/request_handler.py", line 244, in _process_response
    raise PyarrResourceNotFound("Resource not found")
pyarr.exceptions.PyarrResourceNotFound: Resource not found
```

**Comment by lakshyaGoel** [comment]
There were some permission issues with the directories it was trying to access.

**Comment by lakshyaGoel** [comment]
There were some permission issues with the directories it was trying to access.

**Comment by rfsbraz** [comment]
Glad you figured it out! I'll see if I can add a permission check at startup to avoid these
