### ISSUE TITLE
ValueError from Tautulli

### ISSUE THREAD

**Issue by drag0n141** [rfsbraz/deleterr#32]
Hi, i am getting this error when i am start the docker. I am want to use only radarr and my movies library. Tautulli, Plex, Radarr and Trakt is added. And it says at start "Got xxx Movies" from Radarr and Plex.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/app/deleterr.py", line 676, in <module>
    main()
  File "/app/app/deleterr.py", line 672, in main
    Deleterr(config)
  File "/app/app/deleterr.py", line 56, in __init__
    self.process_radarr()
  File "/app/app/deleterr.py", line 217, in process_radarr
    movie_activity = self.tautulli.get_activity(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 49, in get_activity
    last_activity[metadata["guid"]] = self._prepare_activity_entry(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 99, in _prepare_activity_entry
    "year": int(metadata["year"]),
            ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by rfsbraz** [comment]
Some movies can be missing an year when retrieving from tautulli, I need to provide a default. Easy fix!

**Comment by drag0n141** [comment]
Still got some error.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/app/deleterr.py", line 676, in <module>
    main()
  File "/app/app/deleterr.py", line 672, in main
    Deleterr(config)
  File "/app/app/deleterr.py", line 56, in __init__
    self.process_radarr()
  File "/app/app/deleterr.py", line 217, in process_radarr
    movie_activity = self.tautulli.get_activity(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 49, in get_activity
    last_activity[metadata["guid"]] = self._prepare_activity_entry(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/tautulli.py", line 99, in _prepare_activity_entry
    "year": int(metadata.get("year", 0))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by rfsbraz** [comment]
🤦
