### ISSUE TITLE
TypeError: 'NoneType' object is not iterable since v0.0.13

### ISSUE THREAD

**Issue by jpdsc** [rfsbraz/deleterr#77]
Hi,

Since version: [v0.0.13], I'm getting

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/app/deleterr.py", line 745, in <module>
    main()
  File "/app/app/deleterr.py", line 741, in main
    Deleterr(config)
  File "/app/app/deleterr.py", line 64, in __init__
    self.process_radarr()
  File "/app/app/deleterr.py", line 212, in process_radarr
    if not library_meets_disk_space_threshold(library, radarr):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/deleterr.py", line 697, in library_meets_disk_space_threshold
    for item in library.get("disk_size_threshold"):
TypeError: 'NoneType' object is not iterable
1
```

Seems to be related to the new disk_size_threshold function. I have not set this up in the config file.

Any other details needed; let me know.

**Comment by rfsbraz** [comment]
Ouch. What an oversight, fixing this quickly

**Comment by rfsbraz** [comment]
Done! Please point your image to `v0.0.14`!
